### ISSUE TITLE
Document is now obsolete

### ISSUE THREAD

**Issue by ahilden** [ibm-cloud-docs/Db2onCloud#25]
The following document is only applicable for V1 Db2 on Cloud service instances.  We no longer support provisioning these so this can be removed: https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-key-protect

Note: This topic is the good one and should remain - https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-key-protect-v2

**Comment by rimask** [comment]
Done.
