### ISSUE TITLE
How to connect AWS IBM Db2 Developer-C 11.1.4.4 from my local machine

### ISSUE THREAD

**Issue by devopsdymyr** [ibm-cloud-docs/Db2onCloud#41]
I have followed this steps to spinup my db2 instance which is working fine but not able to connect from any gui tools.

Let me know how to access from  db2 database from any other tools or service or if you can guide.

**Comment by rimask** [comment]
@devopsdymyr 
Have a look at our "Connecting" documentation:
https://cloud.ibm.com/docs/services/Db2onCloud?topic=Db2onCloud-connect_ov

Issues opened in this GitHub repo are for edits or improvements to documentation. This is not the place to open support issues when you have problems. To get help and support, please follow the instructions here:
https://cloud.ibm.com/docs/services/Db2onCloud?topic=Db2onCloud-help_support
