### ISSUE TITLE
python : ImportError: dlopen failed: "/data/data/org.teammate.teammate/files/app/ibm_db_dlls/ibm_db.dll" has bad ELF magic #454

### ISSUE THREAD

**Issue by kulvir244** [ibm-cloud-docs/Db2onCloud#42]
i am trying to use ibm-db in my python-android app. i am getting below error when app runs on android phone:-
python : ImportError: dlopen failed: "/data/data/org.teammate.teammate/files/app/ibm_db_dlls/ibm_db.dll" has bad ELF magic

please help to find a solution for this, i am trying to solve it from days.

**Comment by rimask** [comment]
@kulvir244 
I'm sorry to hear that you're having difficulties with your newly developed app. Unfortunately, issues opened here are for problems with documentation. 

For help and support matters, please see the following topic:
https://cloud.ibm.com/docs/services/Db2onCloud?topic=Db2onCloud-help_support

Thank you.
