### ISSUE TITLE
"Exceeded maximum limit of 5 connections. Connection refused"

### ISSUE THREAD

**Issue by SandeepAswathnarayana** [ibm-cloud-docs/Db2onCloud#44]
I understand that the **Db2 on Cloud Lite plan** restricts the number of connections to 5 per user. I am curious to learn how I could resolve this issue while still using my Lite plan. Any inputs or alternatives are greatly appreciated.

Thank you,
Sandeep Aswathnarayana

<img width="960" alt="IBM Db2_connection refused" src="https://user-images.githubusercontent.com/27179238/74749799-b72a6a80-5290-11ea-92d2-cbe1ea93d1e4.PNG">

**Comment by rimask** [comment]
@SandeepAswathnarayana 
I'm sorry to say that I cannot help you to resolve your issue. I am a technical writer and not part of IBM Support. 

Issues opened in this GitHub repo are for edits or improvements to documentation. This is not the place to open support issues when you have problems. To get help and support, please follow the instructions here:
https://cloud.ibm.com/docs/services/Db2onCloud?topic=Db2onCloud-help_support

**Comment by SandeepAswathnarayana** [comment]
@rimask Thanks for reverting. I believe the 'Help and support' page has a wrong hyperlink to open issues that eventually landed me here. Now, I notice that this is the docs repo. Sorry for the inconvenience caused.
