### ISSUE TITLE
Error is preventing me from using this service. 

### ISSUE THREAD

**Issue by xor1011** [ibm-cloud-docs/Db2onCloud#49]
[jcc][t4][2013][11249][4.26.14] Connection authorization failure occurred. Reason: User ID or Password invalid. ERRORCODE=-4214, SQLSTATE=28000

**Comment by rimask** [comment]
Issues opened here are for making corrections or additions to documentation for the Db2 on Cloud service. 

For Support issues, please see [Getting support](https://cloud.ibm.com/docs/get-support?topic=get-support-getting-customer-support) for your support options.
