### ISSUE TITLE
Help (Error to open Console)

### ISSUE THREAD

**Issue by Hajer-Thabet** [ibm-cloud-docs/Db2onCloud#51]
When I click in Open Console I got this error 
{"trace":"d1524b830e8821f07aedbdcabe095180","errors":[{"code":"authentication_failure","message":"HWCSEC0016E: Authentication failed for SSO. This may caused by failed to generate access token in console side using existing credentials.","target":{"type":"","name":""},"more_info":""}]}
Please help me

**Comment by rimask** [comment]
Issues opened here are for problems with documentation, not for service support. Please consult the "Help and support" page for options regarding how to obtain help to resolve your service problem.

https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-help_support
