### ISSUE TITLE
New Topic under Administration - Deleting your data

### ISSUE THREAD

**Issue by ahilden** [ibm-cloud-docs/Db2onCloud#55]
Can you please create a page called "Deleting your data" and make available under the administrative tab?

### Deleting a Database
When a service instance is deleted the database that it provides is also removed. This will delete any online data and logs as well as database backups.  The data will not be recoverable after this action.

### How is the data deleted
All data is encrypted at rest to ensure data is protected at all times using encryption keys stored in a key management service called Key Protect.  When access to those keys is removed, the data is crypto-shredded and cannot be recovered.  When the service instance is deleted the block storage used for the the database is wiped to ensure all data is erased. Any data objects in cloud object storage are also deleted and not recoverable.

### When is the data deleted
There is a soft data deletion period of up to 9 days before all stored data is deleted irrecoverably. 

### Using your own encryption keys to delete data
You can use your own encryption keys to delete data. This is called cryptoshredding. Once the key is deleted your data is unrecoverable and unreadable by anyone.

Key Protect allows you to initiate a force delete of a key that is in use by various IBM Cloud™ services, including your Db2 on Cloud service instances. Deleting a key that is in use on your deployment locks the disks containing your data when the key is requested again. You can have this occur right away by contact IBM Support or by deleting your service instance as well.  Key deletion is sent to the LogDNA Activity Tracker as kms.secrets.delete.

If you delete a deployment that is protected with your Key Protect key, the deployment remains registered against the key for the duration of the soft-deletion period (up to 9 days). If you need to delete the key in the soft-deletion period, you have to force delete the key. After the soft-deletion period the key can be deleted without the force. You can check the association between the key and your deployment to determine when you can delete the key.

### Deleting data in your database
The Db2 database stores data in pages on block storage.  When DELETE or TRUNCATE operations are performed that data is no longer accessible unless you are using TEMPORAL tables. The physical pages that contain the data are not immediately erased and may still exist on the disk but will be overwritten as needed. There is no ability for recovery of this data. The database provides the REORG and REDUCE MAX capability to reclaim this space for other activities or it will be reused when the database needs to store more data.

**Comment by rimask** [comment]
Completed on staging:
https://test.cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-del_db

**Comment by rimask** [comment]
Approved by Andrew.

**Comment by rimask** [comment]
Published:
https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-del_db
