### ISSUE TITLE
DB2 Management API Link points to v3 instead of v4

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/Db2onCloud#58]
The DB2 Management API (https://cloud.ibm.com/apidocs/db2-on-cloud) redirects to `v3` (https://cloud.ibm.com/apidocs/db2-on-cloud/db2-on-cloud-v3) of the API. It states its a legacy API.

Update redirect to `v4` (https://cloud.ibm.com/apidocs/db2-on-cloud/db2-on-cloud-v4)

**Comment by levitj** [comment]
This is as designed. Users of the V3 console have the API link hard coded and its desirable to have them be redirected to the legacy doc. When the legacy console is no longer available, we will indeed update that redirect to the latest doc.

**Comment by rimask** [comment]
Closing.
