### ISSUE TITLE
OPEN CONSOLE PROBLEM

### ISSUE THREAD

**Issue by ravij25** [ibm-cloud-docs/Db2onCloud#59]
{"trace":"772f26353d5a0c0acd3ab85f8c6b67d2","errors":[{"code":"authentication_failure","message":"HWCSEC0016E: Authentication failed for SSO. This may caused by failed to generate access token in console side using existing credentials.","target":{"type":"","name":""},"more_info":""}]}

**Comment by rimask** [comment]
@ravij25  Issues opened here are for corrections and updates to documentation. We do not provide support through issues that are opened here.

Please consult the [Help and support](https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-help_support) topic for support options.
