### ISSUE TITLE
Cannot cannot to Db2

### ISSUE THREAD

**Issue by john7207** [ibm-cloud-docs/Db2onCloud#68]
{"trace":"87266e915378cb1c0cc48411f1b6e7b1","errors":[{"code":"authentication_failure","message":"HWCSEC0016E: Authentication failed for SSO. This may caused by failed to generate access token in console side using existing credentials.","target":{"type":"","name":""},"more_info":""}]}

**Comment by rimask** [comment]
Issues opened here are for errors or changes to documentation.

For support issues as the one that you are currently facing, please see the "Help and support" topic for support options:
https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-help_support
