### ISSUE TITLE
Upgrading Db2 on Cloud plans - No mention that you will need to make a code change if migrating CF application

### ISSUE THREAD

**Issue by jpwsutton** [ibm-cloud-docs/Db2onCloud#9]
Hi,

I'm currently working my way though the process here: https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-upgrade_plans only to find that you've changed the VCAP services JSON and didn't mention it.

It should be made very clear that if you are migrating an application that used the previous DB2 service, you will likely need to change how you access the VCAP_SERVICES JSON object. This will require a code change in applications resulting in a more complex migration path.

**Comment by rimask** [comment]
Published:
https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-upgrade_plans

https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-connect_options
